### ISSUE TITLE
UI not updating for OBS install

### ISSUE THREAD

**Issue by matthew-hagemann** [ubuntu/app-center#1347]
I tried to install OBS Studio and ran into problems with the app reflecting the current state of the installation.

It never updated past the install button being green. If I click it nothing happens. However, OBS did in fact install in the background. Clicking the button yielded a few errors:

Clicking install while it was actually installing in the background:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SnapdException(kind: snap-change-conflict, message: snap "obs-studio" has "install-snap" change in progress)
#0      _SnapdErrorResponse.result (package:snapd/src/snapd_client.dart:1164)
#1      SnapdClient._postAsync (package:snapd/src/snapd_client.dart:1564)
<asynchronous suspension>
#2      SnapdClient.install (package:snapd/src/snapd_client.dart:1442)
<asynchronous suspension>
#3      SnapModel._snapAction (package:app_store/src/snapd/snap_model.dart:138)
<asynchronous suspension>
```

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SnapdException(kind: auth-cancelled, message: cancelled)
#0      _SnapdErrorResponse.result (package:snapd/src/snapd_client.dart:1164)
#1      SnapdClient._postAsync (package:snapd/src/snapd_client.dart:1564)
<asynchronous suspension>
#2      SnapdClient.remove (package:snapd/src/snapd_client.dart:1469)
<asynchronous suspension>
#3      SnapModel._snapAction (package:app_store/src/snapd/snap_model.dart:138)
<asynchronous suspension>
```
Clicking install now that it is installed yields:
```

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SnapdException(kind: snap-already-installed, message: snap "obs-studio" is already installed)
#0      _SnapdErrorResponse.result (package:snapd/src/snapd_client.dart:1164)
#1      SnapdClient._postAsync (package:snapd/src/snapd_client.dart:1564)
<asynchronous suspension>
#2      SnapdClient.install (package:snapd/src/snapd_client.dart:1442)
<asynchronous suspension>
#3      SnapModel._snapAction (package:app_store/src/snapd/snap_model.dart:138)
<asynchronous suspension>
```

Closing and opening the store now gives me the option to open/uninstall OBS.

**Comment by d-loose** [comment]
#1396 introduced error dialogs for those cases
