### ISSUE TITLE
 Can't install with classic confinement 

### ISSUE THREAD

**Issue by matthew-hagemann** [ubuntu/app-center#1348]
I tried installing Eclipse through the store. No UI update when I click install, but got an error indicating that it requires classic confinement:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SnapdException(kind: snap-needs-classic, message: snap "eclipse" requires classic confinement)
#0      _SnapdErrorResponse.result (package:snapd/src/snapd_client.dart:1164)
#1      SnapdClient._postAsync (package:snapd/src/snapd_client.dart:1564)
<asynchronous suspension>
#2      SnapdClient.install (package:snapd/src/snapd_client.dart:1442)
<asynchronous suspension>
#3      SnapModel._snapAction (package:app_store/src/snapd/snap_model.dart:138)
<asynchronous suspension>
```

Same story if I try install Emacs, which also requires classic confinement:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SnapdException(kind: snap-needs-classic, message: snap "emacs" requires classic confinement)
#0      _SnapdErrorResponse.result (package:snapd/src/snapd_client.dart:1164)
#1      SnapdClient._postAsync (package:snapd/src/snapd_client.dart:1564)
<asynchronous suspension>
#2      SnapdClient.install (package:snapd/src/snapd_client.dart:1442)
<asynchronous suspension>
#3      SnapModel._snapAction (package:app_store/src/snapd/snap_model.dart:138)
<asynchronous suspension>

```

Trying to install either of these snaps through the cli does require the --classic flag:

```
> sudo snap install emacs
error: This revision of snap "emacs" was published using classic confinement and thus may perform
       arbitrary system changes outside of the security sandbox that snaps are usually confined to,
       which may put your system at risk.

       If you understand and want to proceed repeat the command including --classic.
```

**Comment by d-loose** [comment]
Fixed, see https://github.com/ubuntu/app-center/pull/1352#issuecomment-1706400059
